cmake_minimum_required(VERSION 3.10)
project(anc216emu LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
option(ANC216_WITH_SDL "Build the SDL2 display" OFF)
find_package(Threads REQUIRED)
add_library(anc216core src/cpu.cc src/device.cc src/emem.cc src/avc64.cc src/keyboard.cc)
target_include_directories(anc216core PUBLIC include)
target_link_libraries(anc216core PUBLIC Threads::Threads)
if(ANC216_WITH_SDL)
    find_package(SDL2 REQUIRED)
    target_compile_definitions(anc216core PUBLIC ANC216_WITH_SDL)
    target_include_directories(anc216core PUBLIC ${SDL2_INCLUDE_DIRS})
    target_link_libraries(anc216core PUBLIC ${SDL2_LIBRARIES})
endif()
add_executable(anc216emu src/main.cc src/debug.cc)
target_link_libraries(anc216emu PRIVATE anc216core)
